global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [127.0.0.1:9090]

  - job_name: 'UserService'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [172.17.0.1:8082]  ##you can get it from docker by typing docker command  'docker network ls' and then run below docker command 'docker network inspect <bridge network id>' now you will get gateway and subnet ip. copy gateway IP and paste here.

##To get target IP
##docker network ls
## docker network inspect 8b2550320bee
##run the prometheus by running below docker command
##docker run -d -p 9090:9090 -v E:\springboot-with-actuator\UserService\src\main\resources\prometheus.yml prom/prometheus

#command to run grafana
#docker run -d -p 3000:3000 grafana/grafana
##Grafana URL
#localhost:3000/
#Username: admin
#pass: Avinash!@#1989

#in prometheus URL provide docker container IP where prometheus is running
#you can get Docker container IP by running below command
#  docker inspect <prometheus container ID>
#copy the gateway IP and pass

